// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCQta51rvyCJ8kZFdLU0VFVipidkjTNkI',
    appId: '1:50711093294:web:7d07b84851143bc18fffbf',
    messagingSenderId: '50711093294',
    projectId: 'cool-whatsapp-7721',
    authDomain: 'cool-whatsapp-7721.firebaseapp.com',
    storageBucket: 'cool-whatsapp-7721.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs_RjxRiUHgQ8MqVrzj6sHmATeRKJ3EBI',
    appId: '1:50711093294:android:6a1b88a6bc8385428fffbf',
    messagingSenderId: '50711093294',
    projectId: 'cool-whatsapp-7721',
    storageBucket: 'cool-whatsapp-7721.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh0hWj-CDB9PWKmRZv3SkGh-QX-BvzDqE',
    appId: '1:50711093294:ios:e6361f616bfc401a8fffbf',
    messagingSenderId: '50711093294',
    projectId: 'cool-whatsapp-7721',
    storageBucket: 'cool-whatsapp-7721.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh0hWj-CDB9PWKmRZv3SkGh-QX-BvzDqE',
    appId: '1:50711093294:ios:09cf7daa2a1e15288fffbf',
    messagingSenderId: '50711093294',
    projectId: 'cool-whatsapp-7721',
    storageBucket: 'cool-whatsapp-7721.appspot.com',
    iosBundleId: 'com.example.whatsapp.RunnerTests',
  );
}
